<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-85MDBOU" failures="1" tests="9" name="TestNGpractice.iTestlistner" time="0.064" errors="0" timestamp="2022-09-23T22:21:33 IST" skipped="4">
  <testcase classname="TestNGpractice.iTestlistner" name="testMethod2" time="0.003">
    <failure message="expected [11] but found [10]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [11] but found [10]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at TestNGpractice.iTestlistner.testMethod2(iTestlistner.java:24)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testMethod2 -->
  <system-out/>
  <testcase classname="TestNGpractice.iTestlistner" name="testMethod2" time="0.004">
    <skipped/>
  </testcase> <!-- testMethod2 -->
  <system-out/>
  <testcase classname="TestNGpractice.iTestlistner" name="testMethod2" time="0.012">
    <skipped/>
  </testcase> <!-- testMethod2 -->
  <system-out/>
  <testcase classname="TestNGpractice.iTestlistner" name="testMethod4" time="0.002"/>
  <system-out/>
  <testcase classname="TestNGpractice.iTestlistner" name="testMethod4" time="0.004"/>
  <system-out/>
  <testcase classname="TestNGpractice.iTestlistner" name="testMethod1" time="0.029"/>
  <system-out/>
  <testcase classname="TestNGpractice.iTestlistner" name="testMethod3" time="0.003">
    <skipped/>
  </testcase> <!-- testMethod3 -->
  <system-out/>
  <testcase classname="TestNGpractice.iTestlistner" name="testMethod4" time="0.003"/>
  <system-out/>
  <testcase classname="TestNGpractice.iTestlistner" name="testMethod2" time="0.004">
    <skipped/>
  </testcase> <!-- testMethod2 -->
  <system-out/>
</testsuite> <!-- TestNGpractice.iTestlistner -->
